services:
  app:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:3000"
    environment:
      - NODE_ENV=${APP_ENV}
      - DEBUG=${DEBUG}
    command: sh -c "npm install && npm start && tail -f /dev/null"