services:
  app:
    image: node:16
    build:
      context: .
      dockerfile: Dockerfile
    user: "1000:1000"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge